function getMovies() {
    return [
      {
        id: 1,
        type: "now",
        thumbnail: "casablanca.png",
        src: "casablanca-s.mp4",
        name: "Casablanca",
        cast: "Humphrey Bogart, Ingrid Bergmen",
        director: "Michael Curtiz",
        duration: 130,
      },
      {
        id: 2,
        type: "now",
        thumbnail: "wildlife.jpg",
        src: "wildlife.mp4",
        name: "Big Buck",
        cast: "Big Bunny, Little Fox",
        director: "Forest King",
        duration: 100,
      },
      {
        id: 3,
        type: "now",
        thumbnail: "bigbuck.jpg",
        src: "bigbuck-s.mp4",
        name: "Big Buck",
        cast: "Big Bunny, Little Fox",
        director: "Forest King",
        duration: 100,
      },
      { 
        id: 4,
        type: "upcoming",
        thumbnail: "nature.jpg",
        src: "nature.mp4",
        name: "Nature",
        cast: "Parrot, birds",
        director: "Mother Nature",
        duration: 100,
      },
      {
        id: 5,
        type: "upcoming",
        thumbnail: "barbecue.jpg",
        src: "barbecue.mp4",
        name: "Barbecue",
        cast: "Parrot, birds",
        director: "Mother Nature",
        duration: 200,
      },
      {
        id: 6,
        type: "upcoming",
        thumbnail: "wonders.jpg",
        src: "wonders.mp4",
        name: "wonders",
        cast: "Parrot, birds",
        director: "Mother Nature",
        duration: 100,
      },
    ];
  }